package com.javainuse.soap.wsdl.my_soap_forum.world_corp.us;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2022-06-07T01:06:05.083+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "exemple", 
                  wsdlLocation = "file:/C:/Users/BA61744/Downloads/New folder (27)/soap-master/spring-boot-soap-consumer/src/main/resources/wsdl/task.wsdl",
                  targetNamespace = "us.world_corp.my_soap_forum.wsdl") 
public class Example extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("us.world_corp.my_soap_forum.wsdl", "exemple");
    public final static QName Exemple0 = new QName("us.world_corp.my_soap_forum.wsdl", "exemple_0");
    public final static QName Exemple1 = new QName("us.world_corp.my_soap_forum.wsdl", "exemple_1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/BA61744/Downloads/New folder (27)/soap-master/spring-boot-soap-consumer/src/main/resources/wsdl/task.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Example.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/BA61744/Downloads/New folder (27)/soap-master/spring-boot-soap-consumer/src/main/resources/wsdl/task.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Example(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Example(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Example() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Example(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Example(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Example(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns My_0020SOAP_0020Forum
     */
    @WebEndpoint(name = "exemple_0")
    public My_0020SOAP_0020Forum getExemple0() {
        return super.getPort(Exemple0, My_0020SOAP_0020Forum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns My_0020SOAP_0020Forum
     */
    @WebEndpoint(name = "exemple_0")
    public My_0020SOAP_0020Forum getExemple0(WebServiceFeature... features) {
        return super.getPort(Exemple0, My_0020SOAP_0020Forum.class, features);
    }


    /**
     *
     * @return
     *     returns My_0020SOAP_0020Forum
     */
    @WebEndpoint(name = "exemple_1")
    public My_0020SOAP_0020Forum getExemple1() {
    	
    	return new APIImplementation();
       // return super.getPort(Exemple1, My_0020SOAP_0020Forum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns My_0020SOAP_0020Forum
     */
    @WebEndpoint(name = "exemple_1")
    public My_0020SOAP_0020Forum getExemple1(WebServiceFeature... features) {
        return super.getPort(Exemple1, My_0020SOAP_0020Forum.class, features);
    }

}
